#!/bin/sh

NAME=Lidarr
PACKAGE=lidarr
PKG_PID=lidarr.pid
USER=admin
GROUP=administrators

PKG_PATH=/usr/local/AppCentral/${PACKAGE}
DAEMON_USER="${USER}:${GROUP}"

PKG_BIN_PATH=${PKG_PATH}/bin
PKG_CONF_ROOT=${PKG_PATH}/config
PKG_CONF=${PKG_CONF_ROOT}

LD_LIBRARY_PATH=$PKG_PATH/lib:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PKG_PATH/lib64:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PKG_PATH/usr/lib:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=$PKG_PATH/usr/lib64:${LD_LIBRARY_PATH}

export LD_LIBRARY_PATH PKG_BIN_PATH PKG_CONF_ROOT PKG_CONF
