---
ssh: ascross

package: vim
name: Vim
version: 8.0.1056
architecture: ""
firmware: 2.6.0

config:
  general:
    developer: "Vim"
    website: "http://www.vim.org"
    maintainer: "mafredri"
    email: "mafredri+adm@gmail.com"
    depends:
      - ncurses
    conflicts: []
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  register:
    symbolic-link:
      /bin:
        - "rview"
        - "rvim"
        - "vim"
        - "vimdiff"
    boot-priority:
      start-order: 1
      stop-order: 99

case_sensitive: false
runpath: /usr/local/AppCentral/ncurses/lib
root: /usr
files:
  - /usr/bin/rview
  - /usr/bin/rvim
  - /usr/bin/vim
  - /usr/bin/vimdiff
