---
ssh: ascross

package: tmux
name: tmux
version: 2.6.0
architecture: ""
firmware: 2.6.0

config:
  general:
    developer: "Nicholas Marriott"
    website: "https://tmux.github.io"
    maintainer: "mafredri"
    email: "mafredri+adm@gmail.com"
    depends: []
    conflicts: []
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  register:
    symbolic-link:
      /bin:
        - "tmux"

case_sensitive: false
runpath: /usr/local/AppCentral/tmux/lib
root: /
files:
  - /usr/bin/tmux
  - /usr/lib/libevent-2.1.so*
  - /lib/libncurses.so*
